os: linux

language: go

go:
  - 1.14.x

services:
  - postgresql

env:
  global:
    - APP_DB_USERNAME=postgres
    - APP_DB_PASSWORD=admin1234
    - APP_DB_NAME=postgres

script:
  # Test the code
  - go test -v ./...
  # Build the code
  - CGO_ENABLED=0 GOARCH=amd64 go build -o demo -v ./...